Add wordcount and line count filtering to address #89
epi052/feroxbuster pull request #122
Opened 2020-11-13 20:07 UTC by evanrichter

# word and line count filtering

## Branching checklist
- [x] There is an issue associated with your PR (bug, feature, etc.. if not, create one)
- [x] Your PR description references the associated issue (i.e. fixes #123)
- [x] Code is in its own branch
- [x] Branch name is related to the PR contents
- [x] PR targets master

## Static analysis checks
- [x] All rust files are formatted using `cargo fmt`
- [x] All `clippy` checks pass when running `cargo clippy --all-targets --all-features -- -D warnings -A clippy::unnecessary_unwrap`
- [x] All existing tests pass

## Documentation
- [x] New code is documented using [doc comments](https://doc.rust-lang.org/stable/rust-by-example/meta/doc.html)
- [x] Documentation about your PR is included in the README, as needed

## Additional Tests
- [x] New code is unit tested
- [x] New code is integration tested, as needed
- [x] New tests pass

2020-11-14 18:49 UTC, epi052 requested changes
The PR looks great, thank you!  

Other than what's already noted in the review, lines 479 and 523 in scanner.rs should be updated to read the body of the incoming response.  

Thank you again!

2020-11-14 18:49 UTC, epi052 commented on src/heuristics.rs
>                  let ferox_response = FeroxResponse::from(response, false).await;
```suggestion
                let ferox_response = FeroxResponse::from(response, true).await;
```

2020-11-14 18:49 UTC, epi052 commented on src/heuristics.rs
> +                        "{} {:>8} {:>8} {:>8} Got {} for {} (url length: {})\n",
On lines 92 and 113 of this file, the final message looks like this:

`WLD       3526 Wildcard response is static; auto-filtering 3526 responses; toggle this behavior by using --dont-filter`

They should probably have the same column formatting as the others. (i can't add a comment on the exact lines for w/e reason)

2020-11-14 18:49 UTC, epi052 commented on src/reporter.rs
> +                    "{} {:>8} {:>8} {:>8} {}\n",
Current output:
`200       83      333     3526 https://....`

Proposed:
`200       83l      333w     3526c https://....`

I'm open to other thoughts here, tho the short options for lines, words, and bytes according to the wc command seem pretty intuitive

2020-11-14 18:49 UTC, epi052 commented on src/reporter.rs
> +                    "{} {:>8} {:>8} {:>8} {}\n",
also, the heuristics output should be update to match

2020-11-17 01:41 UTC, evanrichter commented
those changes are incorporated now!

2020-11-17 05:15 UTC, evanrichter commented
as for the clippy [weirdness](https://rust-lang.github.io/rust-clippy/master/#deref_addrof), I confirm that it does not happen in current nightly with versions of stuff:

```
❯ cargo clippy -V
clippy 0.0.212 (f5230fb 2020-11-16)

❯ cargo -V       
cargo 1.49.0-nightly (2af662e22 2020-11-12)

❯ rustc -V
rustc 1.50.0-nightly (f5230fbf7 2020-11-16)
```

The latest commit simply appeases clippy stable, and should be removed in a couple months or so 🤷

2020-11-17 15:45 UTC, epi052 approved these changes

2020-11-17 15:45 UTC, epi052 commented
Changes look good!  i'll keep an eye out for when stable clippy catches up with the current nightly.  Thank you for your help!

2020-11-17 15:46 UTC, merged