Added support for specifying cookies with the `-b` flag
epi052/feroxbuster pull request #444
Opened 2022-01-03 13:30 UTC by 7047payloads

I added some code to accept a `key=value` pair for cookies using the `--cookies` flag or the `-b` shorthand. The cookies can still be added using the longer `--header` flag way.

2022-01-05 01:48 UTC, epi052 commented
Hey there, thanks for taking the time to submit this PR! I'm trying to wrap a few things up, but will review it soon (hopefully this week).  Just wanted to let you know that I see it, thanks again!

2022-01-10 01:50 UTC, epi052 requested changes
Thanks again for the PR! In addition to the review comments, below are a few items we'll need to sort out in order to get it merged. 

- [ ] bump version to 2.5.0
- [documentation](https://epi052.github.io/feroxbuster-docs/docs/)
  - [ ] update [help output section](https://epi052.github.io/feroxbuster-docs/docs/configuration/command-line/)

2022-01-10 01:50 UTC, epi052 commented on src/parser.rs
> +                .multiple(true)
multiple values are allowed in the parser definition, but only a single `Cookie: stuff=things` makes it into the actual request (the last one to be iterated over in the loop).

A single Cookie is preferred, as it's HTTP/1.1 compliant, so let's remove the `multiple(true)` and make sure documentation shows how to send multiple key/values in a single `--cookies` param.

2022-01-10 15:56 UTC, 7047payloads commented
Hey! I made a couple modifications. I'm keeping the multiple flags config set to true. Each `key=value` pair would be supplied to individual `-b` flags. These cookies are coerced together into a single cookie header, joined with semicolons, HTTP/1.1 compliant now.

2022-01-11 02:11 UTC, merged

2022-01-11 02:14 UTC, epi052 commented
Thanks for this! I merged your code along with a few minor tweaks and dependency updates. I'm waiting to get another PR or two merged before i actually tag the 2.5.0 release, but it shouldn't be too long, i don't think.

Thanks again!