Directory Listing & Web Scrapping Links
epi052/feroxbuster pull request #464
Opened 2022-01-16 04:38 UTC by godylockz

Finally a directory fuzzer that handles directory listings AND web scrapping links.

## Branching checklist
- [Yes] There is an issue associated with your PR (bug, feature, etc.. if not, create one)
- [Yes ] Your PR description references the associated issue (i.e. fixes #123456)
- [Yes] Code is in its own branch
- [Yes ] Branch name is related to the PR contents
- [Yes] PR targets main
https://github.com/epi052/feroxbuster/issues/291

## Static analysis checks
- [Yes] All rust files are formatted using `cargo fmt`
- [Yes] All `clippy` checks pass when running `cargo clippy --all-targets --all-features -- -D warnings -A clippy::mutex-atomic`
- [Yes] All existing tests pass

## Documentation
- [ Yes] New code is documented using [doc comments](https://doc.rust-lang.org/stable/rust-by-example/meta/doc.html)
- [N/A] Documentation about your PR is included in the README, as needed

## Additional Tests
- [Added 2 tests] New code is unit tested
- [Added 2 tests] New code is integration tested, as needed
- [Yes] New tests pass

## Notes
For best performance on directory listings, I recommend Redirections and Extract Links are on
2 existing extraction tests required changes to account for the single additional request to directories to check for directory listings

2022-01-16 23:25 UTC, epi052 requested changes
mostly done, there's a few things i want to look at still, but pushing what requests i have now so you have them sooner rather than later

2022-01-17 01:14 UTC, epi052 commented on src/extractor/container.rs
> +                let mut new_url = Url::parse(&self.url).unwrap();
unwrap here leads to runtime problems `thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase', src/extractor/container.rs:461:57`

2022-01-17 01:34 UTC, epi052 commented on src/extractor/container.rs
> +        }
```suggestion
        html.select(&selector)
            .filter(|a| a.value().attrs().any(|attr| attr.0 == html_attr))
            .for_each(|tag| {
                if let Some(link) = tag.value().attr(html_attr) {
                    log::debug!("Parsed link \"{}\" from {}", link, resp_url);

                    let new_url = match Url::parse(&self.url) {
                        Ok(mut absolute) => {
                            absolute.set_path(link);
                            absolute.path().to_owned()
                        } // absolute url
                        Err(_) => link.into(), // relative
                    };

                    if self.add_all_sub_paths(&new_url, links).is_err() {
                        log::warn!("could not add sub-paths from {} to {:?}", new_url, links);
                    }
                }
            });
```

2022-01-17 02:19 UTC, godylockz commented on Cargo.toml
> +select = "*"
Fixed, using scraper!

2022-01-17 03:01 UTC, epi052 commented on src/extractor/container.rs
> +                ferox_print(&msg, &PROGRESS_PRINTER);
```suggestion```

2022-01-17 03:03 UTC, epi052 commented on src/scanner/ferox_scanner.rs
> +            ferox_scan.finish()?;
```suggestion
            self.handles.stats.send(SubtractFromUsizeField(
                TotalExpected,
                progress_bar.length() as usize,
            ))?;

            progress_bar.finish_with_message(&format!("=> {}", style("Directory listing").green()));

            ferox_scan.finish()?;
```

2022-01-17 03:04 UTC, epi052 commented on src/extractor/container.rs
> +use scraper::{Html, Selector};
```suggestion
use scraper::{Html, Selector};
use console::style;
```

2022-01-17 03:05 UTC, epi052 commented on CONTRIBUTING.md
> +The command that will ultimately be used in the CI pipeline for linting is `cargo clippy --all-targets --all-features -- -D warnings -A clippy::mutex-atomic -A clippy::unnecessary_unwrap`.
```suggestion
The command that will ultimately be used in the CI pipeline for linting is `cargo clippy --all-targets --all-features -- -D warnings -A clippy::mutex-atomic`.
```

2022-01-17 03:06 UTC, epi052 commented on .github/pull_request_template.md
> +- [ ] All `clippy` checks pass when running `cargo clippy --all-targets --all-features -- -D warnings -A clippy::mutex-atomic -A clippy::unnecessary_unwrap`
```suggestion
- [ ] All `clippy` checks pass when running `cargo clippy --all-targets --all-features -- -D warnings -A clippy::mutex-atomic`
```

2022-01-17 12:22 UTC, epi052 approved these changes

2022-01-17 12:32 UTC, epi052 commented
great job with this, thank you! merging :fire:

2022-01-17 12:32 UTC, merged

2022-03-09 13:35 UTC, SecT0uch commented
Would it be possible (and wise) not to add the directory to the queue if the listing is empty ?

2022-03-09 22:27 UTC, godylockz commented
> Would it be possible (and wise) not to add the directory to the queue if the listing is empty ?

@SecT0uch Do you have a target that has an example of this that your willing to share? 
If it is deemed repeatable, it would be an easy fix. In the meantime, just cancel the scan on that directory if you manually verified there is not any files within.
This is a "new" feature so there may potentially be bugs. This is something that isn't "broken" per-se. No other directory fuzzing tool will even care that its a directory listing, so at least there's that.
@epi052 I'm actually surprised this occurs?

2022-03-10 09:31 UTC, SecT0uch commented
That would be reproducible like that:
```
mkdir /tmp/empty
cd /tmp/empty
python -m "http.server"
```
You get an empty listing on http://localhost:8000